spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mail_scanner?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: mail_scanner
        password: mail_scanner
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false